services:
  web:
    build: ./app
    ports:
      - 8081
    security_opt:
      - label:disable
    depends_on:
      - service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/index.php"]
      timeout: 5s
      retries: 20
      interval: 5s
      start_period: 30s

  service:
    build:
      context: ./app/skumodel-srv
      args:
        - FLAG
    security_opt:
      - label:disable
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "http://service:4455/index.php"]
      timeout: 5s
      retries: 20
      interval: 5s
      start_period: 30s
    environment:
      - NGINX_PORT=4455