services:
  bookmarks:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - 80
    security_opt:
      - label:disable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 5s
      retries: 20
      interval: 5s
      start_period: 15s