services:
  db:
    build: ./mysql
    expose:
      - 3306
    security_opt:
      - label:disable
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-uroot", "--password=trading_platform_db", "-e", "USE database;"]
      timeout: 5s
      retries: 20
      interval: 5s
      start_period: 30s

  trading_platform:
    build:
      context: ./app
      args:
        - FLAG
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 80
    security_opt:
      - label:disable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 5s
      retries: 20
      interval: 5s
      start_period: 30s