services:
  db:
    build:
      context: ./mysql
      args:
        - FLAG
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge
    security_opt:
      - label:disable
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  app:
    build:
      context: ./app
    ports:
      - 80
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    security_opt:
      - label:disable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/"]
      timeout: 5s
      retries: 20
      interval: 5s
      start_period: 30s